I2C_WRITE(device_address=0x68,field_info={'fieldname': 'i2c_page_sel', 'length': 2, 'registers': [{'REG': '0xFE', 'POS': 0, 'RegisterName': 'Page selection', 'RegisterLength': 8, 'Name': 'i2c_page_sel', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000N', 'Default': '00', 'User': '000000YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}, {'REG': '0xFE', 'POS': 0, 'RegisterName': 'Page selection', 'RegisterLength': 8, 'Name': 'i2c_page_sel', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000N', 'Default': '00', 'User': '000000YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x1)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'otp_burnt_b', 'length': 1, 'registers': [{'REG': '0x40', 'POS': 7, 'RegisterName': 'OTP register 0', 'RegisterLength': 8, 'Name': 'otp_burnt_b', 'Mask': '0x80', 'Length': 1, 'FieldMSB': 7, 'FieldLSB': 7, 'Attribute': 'NNNNNNNN', 'Default': '80', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'vis_vbgr_lev_v', 'length': 3, 'registers': [{'REG': '0x40', 'POS': 3, 'RegisterName': 'OTP register 0', 'RegisterLength': 8, 'Name': 'vis_vbgr_lev_v[2:0]', 'Mask': '0x38', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '80', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x40)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'sar_offs_vbat', 'length': 10, 'registers': [{'REG': '0x40', 'POS': 0, 'RegisterName': 'OTP register 0', 'RegisterLength': 8, 'Name': 'sar_offs_vbat[9:8]', 'Mask': '0x3', 'Length': 2, 'FieldMSB': 9, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '80', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0x41', 'POS': 0, 'RegisterName': 'OTP register 1', 'RegisterLength': 8, 'Name': 'sar_offs_vbat[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'sar_gain_vbat', 'length': 8, 'registers': [{'REG': '0x42', 'POS': 0, 'RegisterName': 'OTP register 2', 'RegisterLength': 8, 'Name': 'sar_gain_vbat[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'sar_gain_temp', 'length': 8, 'registers': [{'REG': '0x43', 'POS': 0, 'RegisterName': 'OTP register 3', 'RegisterLength': 8, 'Name': 'sar_gain_temp[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'sar_gain_loc_temp', 'length': 8, 'registers': [{'REG': '0x44', 'POS': 0, 'RegisterName': 'OTP register 4', 'RegisterLength': 8, 'Name': 'sar_gain_loc_temp[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'vis_abs_res_ctrl_ch1', 'length': 5, 'registers': [{'REG': '0x45', 'POS': 3, 'RegisterName': 'OTP register 5', 'RegisterLength': 8, 'Name': 'vis_abs_res_ctrl_ch1[4:0]', 'Mask': '0xF8', 'Length': 5, 'FieldMSB': 4, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '64', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'vis_abs_res_ctrl_ch2', 'length': 5, 'registers': [{'REG': '0x46', 'POS': 3, 'RegisterName': 'OTP register 6', 'RegisterLength': 8, 'Name': 'vis_abs_res_ctrl_ch2[4:0]', 'Mask': '0xF8', 'Length': 5, 'FieldMSB': 4, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '64', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'vis_abs_res_ctrl_ch3', 'length': 5, 'registers': [{'REG': '0x47', 'POS': 3, 'RegisterName': 'OTP register 7', 'RegisterLength': 8, 'Name': 'vis_abs_res_ctrl_ch3[4:0]', 'Mask': '0xF8', 'Length': 5, 'FieldMSB': 4, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '64', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'vis_abs_res_ctrl_ch4', 'length': 5, 'registers': [{'REG': '0x48', 'POS': 3, 'RegisterName': 'OTP register 8', 'RegisterLength': 8, 'Name': 'vis_abs_res_ctrl_ch4[4:0]', 'Mask': '0xF8', 'Length': 5, 'FieldMSB': 4, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '64', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'cal_az_ext_m', 'length': 12, 'registers': [{'REG': '0x49', 'POS': 0, 'RegisterName': 'OTP register 9', 'RegisterLength': 8, 'Name': 'cal_az_ext_m[11:4]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 11, 'FieldLSB': 4, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0x4A', 'POS': 4, 'RegisterName': 'OTP register 10', 'RegisterLength': 8, 'Name': 'cal_az_ext_m[3:0]', 'Mask': '0xF0', 'Length': 4, 'FieldMSB': 3, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
I2C_WRITE(device_address=0x68,field_info={'fieldname': 'cal_az_int_m', 'length': 12, 'registers': [{'REG': '0x4A', 'POS': 0, 'RegisterName': 'OTP register 10', 'RegisterLength': 8, 'Name': 'cal_az_int_m[11:8]', 'Mask': '0xF', 'Length': 4, 'FieldMSB': 11, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0x4B', 'POS': 0, 'RegisterName': 'OTP register 11', 'RegisterLength': 8, 'Name': 'cal_az_int_m[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'FRO', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
# incomplete 